version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.44.0-jammy
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps chromium
      - run:
          name: Run Playwright tests
          command: npm test
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

workflows:
  build-and-test:
    jobs:
      - test
