version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.44.0-jammy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Playwright browsers
          command: npx playwright install --with-deps chromium
      - run:
          name: Run tests
          command: npx playwright test --config pw.config.js
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

workflows:
  build-and-test:
    jobs:
      - test
